# Generated by Django 4.2 on 2023-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
    ]
